export const SET_DIGIT = 'SET_DIGIT'
export const SET_ACTION = 'SET_ACTION'
export const SET_DOT = 'SET_DOT'
export const SET_FUNC = 'SET_FUNC'
export const DELETE_LAST_SYMBOL = 'DELETE_LAST_SYMBOL'
export const DELETE_RESULT = 'DELETE_RESULT'
export const CALCULATE_FUNC = 'CALCULATE_FUNC'
export const EQUAL = 'EQUAL'
