export const ADD_KEY_HANDLER = 'ADD_KEY_HANDLER'
export const KEY_PRESSED = 'KEY_PRESSED'

export const SET_DIGIT = 'SET_DIGIT'
export const SET_ACTION = 'SET_ACTION'
export const SET_DOT = 'SET_DOT'
export const SET_FUNC = 'SET_FUNC'

export const OPEN_BRACKET = 'OPEN_BRACKET'
export const CLOSE_BRACKET = 'CLOSE_BRACKET'
export const SET_BRACKET = 'SET_BRACKET'

export const CHANGE_SIGN = 'CHANGE_SIGN'
export const CHANGE_TRIGONOMETRIC_SCALE = 'CHANGE_TRIGONOMETRIC_SCALE'

export const DELETE_LAST_SYMBOL = 'DELETE_LAST_SYMBOL'
export const DELETE_RESULT = 'DELETE_RESULT'

export const CALCULATE_FUNC = 'CALCULATE_FUNC'
export const EQUAL = 'EQUAL'
